services:
  postgres:
    image: postgres:16-alpine
    container_name: techmarket-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: TechMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - techmarket_postgres_data:/var/lib/postresql/data

volumes:
  techmarket_postgres_data:
  
